### ISSUE TITLE
Add support for range filters

### ISSUE THREAD

**Issue by axiell-pcg** [comic31/MongoDBQueriesManager#1]
Hi!

currently, the query:

`USER_ID>525&USER_ID<600&skip=10&limit=10` results in the following filter: `{'filter': {'USER_ID': {'$lt': 600}}, 'sort': None, 'skip': 10, 'limit': 10, 'projection': None}`. The current code will overwrite the first limitation filter when the second one is added.

It would be great if the same parameter could be passed twice in order to support range queries.

Thanks!

**Comment by comic31** [comment]
Hello :vulcan_salute: ,

This could be a nice proposal !

I will add this feature as soon as I have some free time :upside_down_face:

**Comment by comic31** [comment]
Hello 👋,

Your proposal has been added into release 1.0.0 (deployed on PyPi 🚀).

⚠️ Into version 1.0.0 `dateparser` is now an extra dependencies (check the [CHANGELOG.md](https://github.com/comic31/MongoDBQueriesManager/blob/main/CHANGELOG.md)).
